LayUIDemo/Controllers/MallController.cs
using LayUIDemo.Models;
using mall;
using PetaPoco;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayUIDemo.Controllers
{
    public class MallController : Controller
    {
        public ActionResult PartV()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }/// <summary>
         /// 获取用户列表
         /// </summary>
         /// <param name="userName"></param>
         /// <param name="PageSize"></param>
         /// <param name="page"></param>
         /// <returns></returns>
        public ActionResult GetUerList(string userName, int limit, int page)
        {
            Sql sql = new Sql();
            int totalAmount;
            try
            {
                using (var db = new LayUIDemo.Models.DBMall())
                {

                    if (!string.IsNullOrEmpty(userName))
                    {
                        //sql.Append("where UserName=@0", userName);
                        var query = from p in db.Userinfo
                                    where p.UserName == userName
                                    orderby p.CreateTime
                                    select p;
                        totalAmount = query.Count();
                        return Json(ResultTemp<UserInfo>.OK(query.Skip((page - 1) * limit).Take(limit).ToList(), totalAmount), JsonRequestBehavior.AllowGet);
                    }
                    // var result = db.Page<UserInfo>(page, limit, sql);
                    var result = from p in db.Userinfo
                                 orderby p.CreateTime
                                 select p;
                    totalAmount = result.Count();
                    return Json(ResultTemp<UserInfo>.OK(result.Skip((page - 1) * limit).Take(limit).ToList(), totalAmount), JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {

                throw;
            }
        }
        [HttpGet]
        // GET: Mall
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(UserInfo userInfo)//
        {
            userInfo.CreateTime = DateTime.Now;

            try
            {
                using (var db = new mallDB())
                {
                    if (db.Exists<UserInfo>("username=@0", userInfo.UserName))
                    {
                        return Content("注册失败:用户名已经存在");
                    }
                    var userId = db.Insert(userInfo);
                    if ((int)(userId) > 0)
                    {
                        return Content("注册成功");
                    }
                    return Content("注册失败");
                }
            }
            catch (Exception e)
            {
                return Content("发生错误:" + e.Message);
            }
        }
        public ActionResult Main()
        {
            return View();
        }
    }
}

LayUIDemo/Views/Mall/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = null;
}
<link href="~/Plugins/layui/css/layui.css" rel="stylesheet" />
<script src="~/Plugins/layui/layui.js"></script>
<fieldset class="layui-elem-field layui-field-title" style="margin-top: 50px;">
    <legend>初始赋值演示</legend>
</fieldset>

<form class="layui-form" action="">
    <div class="layui-form-item">
        <label class="layui-form-label">用户名</label>
        <div class="layui-input-block">
            <input type="text" id="username" name="UserName" lay-verify="name" autocomplete="off" value="" placeholder="请输入用户名" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">密码</label>
        <div class="layui-input-block">
            <input type="password" name="Password" lay-verify="pwd" value="" placeholder="请输入密码" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
            <label class="layui-form-label">爱好</label>
            <div class="layui-input-block">
                <select name="Interest" lay-filter="aihao">
                    <option value=""></option>
                    <option value="0">写作</option>
                    <option value="1">阅读</option>
                    <option value="2">游戏</option>
                    <option value="3">音乐</option>
                    <option value="4">旅行</option>
                </select>
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">业余爱好</label>
            <div class="layui-input-block" id="hoppy">
                <input type="checkbox" value="1" name="like[write]" title="写作">
                <input type="checkbox" value="2" name="like[read]" title="阅读">
                <input type="checkbox" value="3" name="like[daze]" title="发呆">
            </div>
        </div>

    @*<div class="layui-form-item">
            <label class="layui-form-label">开关</label>
            <div class="layui-input-block">
                <input type="checkbox" name="close" lay-skin="switch" lay-text="ON|OFF">
            </div>
        </div>*@

    <div class="layui-form-item">
            <label class="layui-form-label">性别</label>
            <div class="layui-input-block">
                <input type="radio" name="Sex" value="1" title="男" checked="">
                <input type="radio" name="Sex" value="0" title="女">
            </div>
        </div>
        <div class="layui-form-item layui-form-text">
            <label class="layui-form-label">一句话</label>
            <div class="layui-input-block">
                <textarea placeholder="请输入内容" class="layui-textarea" name="Remark"></textarea>
            </div>
        </div>

    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-submit="" lay-filter="demo1">注册</button>
            <button class="layui-btn layui-btn-primary" id="cancel">取消</button>
        </div>
    </div>
</form>
<script>
    layui.use(['form', 'layer'], function () {
        var form = layui.form; //只有执行了这一步，部分表单元素才会自动修饰成功
        var layer = layui.layer;
        var $ = layui.$;
        //表单验证规则
        form.verify({
            name: function (data) {
                if (data.trim() == '') {
                    return "请输入用户名"
                }
                if (data.length > 6 || data.length<2) {
                    return "请输入长度在2-6位之间的用户名"
                }
            },
            pwd: function (data) {
                if (data.trim()=='') {
                    return "请输入密码"
                }
            }
        })

        //但是，如果你的HTML是动态生成的，自动渲染就会失效
        //因此你需要在相应的地方，执行下述方法来手动渲染，跟这类似的还有 element.init();
        //layer.msg('hello')
        form.on('submit(demo1)', function (data) {
            $.post(
                {
                url: '@Url.Action("Add","Mall")',
                data: data.field,
                success: function (res) {
                    layer.msg(res)
                }
                })
            return false;
        })
        $('#cancel').on('click', function () {
            parent.layer.close(parent.layer.index);
        })
    });
</script>

LayUIDemo/Views/Mall/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}


<div class="layui-input-inline">
    <input type="text" autocomplete="off" placeholder="用户名" id="s_userName" style="width:200px;margin:5px" value="" class="layui-input" />
</div>
<div class="layui-input-inline">
    <button class="layui-btn" lay-submit="" id="search">搜索</button>
    <button class="layui-btn" lay-submit="" id="add_user">注册</button>
</div>
<table id="demo" lay-filter="test"></table>
<script>
    layui.use(['table','layer'], function () {
        var table = layui.table;
        var layer = layui.layer;
        var $ = layui.$;
        table.render({
            elem: '#demo',
            url: '@Url.Action("GetUerList","Mall")',
            page: true,
            cols: [[
                { field: 'UserId', title: 'ID', sort: true, fixed: 'left' },
                { field: 'UserName', title: '用户名' },
                {
                    field: 'Sex', title: '性别', sort: true, templet: function (d) {
                        return d.Sex == '0' ? '女' : '男';
                    }
                }
            ]]
        });
        $('#search').on('click', function () {
            table.reload('demo',
                {
                    where: {
                        userName:$('#s_userName').val()
                    }
                }
            )
        })
        $('#add_user').on('click', function () {
            layer.open({
  type: 2,
                content: '@Url.Action("Add","Mall")',
                area: ['900px', '700px'],
                maxmin: true
});
        })
    })
</script>

LayUIDemo/Views/Mall/Main.cshtml
@{
    ViewBag.Title = "Main";
    Layout = null;
}

<link href="~/Plugins/layui/css/layui.css" rel="stylesheet" />
<script src="~/Plugins/layui/layui.js"></script>
<div class="layui-tab" lay-filter="test">
    <ul class="layui-tab-title">
        <li class="layui-this" lay-id="11">用户列表1</li>
        <li lay-id="22">用户列表2</li>

    </ul>
    <div class="layui-tab-content">
        <div id="c1" class="layui-tab-item layui-show">
            @{
                Html.RenderAction("Index", "Mall");
            }
        </div>
        <div id="c2" class="layui-tab-item">用户列表2</div>
    </div>
</div>
<script>

    layui.use('element', function () {
        var element = layui.element();
        var $ = layui.$;
        element.on('tab(test)', function (data) {
            if (data.index == 0) {
                $.get('/Mall/Index', function (html) {
                    $("#c2").empty();
                    $(".layui-show").append(html);
                })
            }
            //element.render('tab');
            if (data.index == 1) {
                $.get('/Mall/Index', function (html) {
                    $("#c1").empty();
                    $(".layui-show").append(html);
                })
            }
        });

    });
</script>

LayUIDemo/Views/Mall/PartV.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}

    <div>djsaflk</div>
<button id="btn1">按钮</button>
<div>用户名:<input type="text" value="" /></div>
<script>
    $(function () {
        $('#btn1').click(function () {
            alert('按钮点击了')
        })
    })
</script>